/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.ClaseConexion;
import Clases.ClasePrestamoHipotecario;
import Clases.ClasePrestamoPersonal;
import Clases.ClasePrestamos;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josue
 */
public class frmPrestamo extends javax.swing.JFrame {

    /**
     * Creates new form frmPrestamoHipotecario
     */
    PreparedStatement pps=null;
    ResultSet rs = null;
    ClaseConexion con = new ClaseConexion(); //Nombre de la clase
    Connection cn = con.getConnection();
    
    ButtonGroup TipoPrestamo = new ButtonGroup();
    ClasePrestamoPersonal objPersonal = new ClasePrestamoPersonal();
    ClasePrestamoHipotecario objHipotecario = new ClasePrestamoHipotecario();
    
    public frmPrestamo() {
        initComponents();
        TipoPrestamo.add(btnPersonal);
        TipoPrestamo.add(btnHipotecario);
        btnBuscarActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumPrestamo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnPersonal = new javax.swing.JRadioButton();
        btnHipotecario = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamos = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("# de Prestamo:");
        jLabel1.setToolTipText("");

        jLabel2.setText("Nombre Cliente:");
        jLabel2.setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Prestamo"));

        btnPersonal.setText("Personal");
        btnPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalActionPerformed(evt);
            }
        });

        btnHipotecario.setText("Hipotecario");
        btnHipotecario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHipotecarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPersonal)
                    .addComponent(btnHipotecario))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnPersonal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHipotecario)
                .addContainerGap())
        );

        tblPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPrestamosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPrestamos);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel3.setText("Codigo:");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdicionar)
                        .addGap(17, 17, 17)
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumPrestamo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(btnBuscar)
                                .addGap(34, 34, 34))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigo)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNumPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdicionar)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar)
                            .addComponent(btnSalir)
                            .addComponent(btnLimpiar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalActionPerformed
        // TODO add your handling code here:
        frmPrestamoPersonal frm = new frmPrestamoPersonal();
        frm.setVisible(true);
    }//GEN-LAST:event_btnPersonalActionPerformed

    private void btnHipotecarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHipotecarioActionPerformed
        // TODO add your handling code here:
        frmPrestamoHipotecario frm = new frmPrestamoHipotecario();
        frm.setVisible(true);
    }//GEN-LAST:event_btnHipotecarioActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        String msj;
        ClasePrestamos prestamo = new ClasePrestamos();
        prestamo.setNumeroPrestamos(Integer.parseInt(txtNumPrestamo.getText()));
        prestamo.setNombreCliente(txtNombre.getText());
        
        if(btnPersonal.isSelected()){
            msj = objPersonal.toString();
            prestamo.setTipoPrestamo(1);
        }else{
            msj = objHipotecario.toString();
            prestamo.setTipoPrestamo(2);
        }
        
        try{
            pps = cn.prepareStatement("INSERT INTO prestamo(idPrestamo, nombreCliente, tipoPrestamo)"
                    + " VALUES(?, ?, ?)");
            
            pps.setInt(1, prestamo.getNumeroPrestamos());
            pps.setString(2, prestamo.getNombreCliente());
            pps.setInt(3, prestamo.getTipoPrestamo());
            
            pps.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Prestamo Agregado con Exito.");
        }catch(SQLException ex){
            java.util.logging.Logger.getLogger(ClasePrestamos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(btnPersonal.isSelected()){
            AggPersonal();
        }else{
            AggHipotecario();
        }
        JOptionPane.showMessageDialog(rootPane, msj);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigo.getText();
        String where = "";
        
        if(!"".equals(codigo)){
            where = " WHERE idPrestamo = '"+ codigo +"'";
        }
        
        try{
            DefaultTableModel modelo = new DefaultTableModel();
            tblPrestamos.setModel(modelo);
            
            String SQL = "SELECT * FROM prestamo " + where;
            pps = cn.prepareStatement(SQL);
            rs = pps.executeQuery();
            
            java.sql.ResultSetMetaData rsMD = rs.getMetaData();
            int cantidadColumnas = rsMD.getColumnCount();
            
            modelo.addColumn("Numero");
            modelo.addColumn("Cliente");
            modelo.addColumn("Tipo");
            
            while(rs.next()){
                Object[] filas = new Object[cantidadColumnas];
                
                for(int i=0; i<cantidadColumnas; i++){
                    filas[i] = rs.getObject(i+1);
                }
                
                modelo.addRow(filas);
            }
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error " + ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPrestamosMouseClicked
        // TODO add your handling code here:
        int seleccion = tblPrestamos.rowAtPoint(evt.getPoint());
        txtNumPrestamo.setText(String.valueOf(tblPrestamos.getValueAt(seleccion, 0)));
        txtNumPrestamo.setEnabled(false);
        txtNombre.setText(String.valueOf(tblPrestamos.getValueAt(seleccion, 1)));
    }//GEN-LAST:event_tblPrestamosMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        try{
            pps = cn.prepareStatement("UPDATE prestamo SET nombreCliente=? WHERE idPrestamo=?");
            
            pps.setString(1, txtNombre.getText());
            pps.setString(2, txtNumPrestamo.getText());
            
            pps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro Modificado");
        }catch(SQLException ex){
            java.util.logging.Logger.getLogger(ClasePrestamos.class.getName()).log(Level.SEVERE, null, ex);
        }
        Limpiar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try{
            pps = cn.prepareStatement("DELETE FROM prestamo WHERE idPrestamo=?");
            
            pps.setString(1, txtNumPrestamo.getText());
            
            pps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro Eliminado");
        }catch(SQLException ex){
            java.util.logging.Logger.getLogger(ClasePrestamos.class.getName()).log(Level.SEVERE, null, ex);
        }
        Limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void AggPersonal(){
        try{
            pps = cn.prepareStatement("INSERT INTO detallepersonal(aval1, aval2, sueldo, Prestamo)"
                    + " VALUES(?, ?, ?, ?)");
            
            pps.setString(1, objPersonal.getAval1());
            pps.setString(2, objPersonal.getAval2());
            pps.setDouble(3, objPersonal.getSueldo());
            pps.setInt(4, objPersonal.getNumeroPrestamos());
            
            pps.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Prestamo Agregado con Exito.");
            Limpiar();
        }catch(SQLException ex){
            java.util.logging.Logger.getLogger(ClasePrestamos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void AggHipotecario(){
        try{
            pps = cn.prepareStatement("INSERT INTO detallehipotecario (numCatastral, ubicacion, valor, Prestamo)"
                    + " VALUES(?, ?, ?, ?)");
            
            pps.setString(1, objHipotecario.getNumCatastral());
            pps.setString(2, objHipotecario.getUbicacion());
            pps.setDouble(3, objHipotecario.getValor());
            pps.setInt(4, objHipotecario.getNumeroPrestamos());
            
            pps.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Prestamo Agregado con Exito.");
            Limpiar();
        }catch(SQLException ex){
            java.util.logging.Logger.getLogger(ClasePrestamos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void Limpiar(){
        txtNumPrestamo.setText(null);
        txtNumPrestamo.setEnabled(true);
        txtNombre.setText(null);
        TipoPrestamo.clearSelection();
        
        btnBuscarActionPerformed(null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JRadioButton btnHipotecario;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JRadioButton btnPersonal;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPrestamos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumPrestamo;
    // End of variables declaration//GEN-END:variables
}
